export const INCREMENT_COOKIES = 'INCREMENT_COOKIES';
export const BUY_ITEM = 'BUY_ITEM';
export const AUTO_INCREMENT = 'AUTO_INCREMENT';
export const LOAD_SAVE = 'LOAD_STORE_DATA';
export const ADD_COOKIES = 'ADD_COOKIES';